import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, setPersistence, browserLocalPersistence, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, signInWithRedirect, getRedirectResult, GoogleAuthProvider, OAuthProvider, sendPasswordResetEmail, sendEmailVerification, updateProfile, signOut } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, doc, addDoc, setDoc, updateDoc, deleteDoc, onSnapshot, query, orderBy, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-functions.js';
import { firebaseConfig, firebaseConfigured } from './firebase-config.js';

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const state = { user:null, transactions:[], accounts:[], goals:[], categories:[], month:new Date().getMonth(), year:new Date().getFullYear(), filter:'all', txType:'expense', editingTxId:null, unsubscribers:[] };
const DEFAULT_CATEGORIES = { income:['Nómina','Trabajo autónomo','Rendimientos','Ventas','Reembolso','Otros ingresos'], expense:['Vivienda','Alimentación','Transporte','Salud','Educación','Ocio','Suscripciones','Compras','Impuestos','Otros gastos'] };
const PAYMENT_METHODS = { pix:'Bizum',cash:'Efectivo',debit_card:'Tarjeta de débito',credit_card:'Tarjeta de crédito',bank_transfer:'Transferencia bancaria',other:'Otro origen' };
const MONTHS = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const ICONS = {Vivienda:'⌂',Alimentación:'●',Transporte:'◆',Salud:'✚',Educación:'▤',Ocio:'☆',Suscripciones:'↻',Compras:'▦',Impuestos:'%',Nómina:'€','Trabajo autónomo':'◈',Rendimientos:'↗',Ventas:'▣',Reembolso:'↩'};
let auth, db, functions, deferredInstall, confirmHandler;

function money(value){ return Number(value||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'}); }
function esc(value){ return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function dateES(value){ return new Date(`${value}T12:00:00`).toLocaleDateString('es-ES'); }
function firstName(user=state.user){ return (user?.displayName||user?.email?.split('@')[0]||'tú').trim().split(/\s+/)[0]; }
function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2800); }
function monthTransactions(){ return state.transactions.filter(item=>{const d=new Date(`${item.date}T12:00:00`);return d.getMonth()===state.month&&d.getFullYear()===state.year;}); }
function accountBalance(account){ return Number(account.openingBalance||0)+state.transactions.filter(item=>item.accountId===account.id).reduce((sum,item)=>sum+(item.type==='income'?Number(item.amount):-Number(item.amount)),0); }
function categoriesFor(type){return [...DEFAULT_CATEGORIES[type],...state.categories.filter(item=>item.type===type).map(item=>item.name)].filter((name,index,all)=>all.findIndex(item=>item.toLocaleLowerCase('es-ES')===name.toLocaleLowerCase('es-ES'))===index);}
function errorMessage(error){ const messages={'auth/invalid-credential':'Correo electrónico o contraseña incorrectos.','auth/email-already-in-use':'Este correo electrónico ya está registrado.','auth/weak-password':'Usa una contraseña más segura, con al menos 8 caracteres.','auth/invalid-email':'Introduce un correo electrónico válido.','auth/popup-closed-by-user':'El acceso se ha cancelado.','auth/too-many-requests':'Demasiados intentos. Espera unos minutos.','auth/network-request-failed':'Comprueba tu conexión a internet.','auth/requires-recent-login':'Vuelve a iniciar sesión antes de eliminar tu cuenta.'}; return messages[error?.code]||error?.message||'No se ha podido completar la operación. Inténtalo de nuevo.'; }
function setBusy(form,busy){ $$(`${form} button`).forEach(button=>button.disabled=busy); }

function switchAuth(tab){ const register=tab==='register'; $$('.auth-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.authTab===tab)); $('#login-form').hidden=register; $('#register-form').hidden=!register; }
function showAuth(){ $('#loading-screen').hidden=true; $('#app-shell').hidden=true; $('#auth-screen').hidden=false; }
function showApp(){ $('#loading-screen').hidden=true; $('#auth-screen').hidden=true; $('#app-shell').hidden=false; }

async function start(){
  bindEvents();
  if(!firebaseConfigured){ showAuth(); $('#config-warning').hidden=false; $$('#login-form button,#register-form button,.social-button').forEach(button=>button.disabled=true); return; }
  const app=initializeApp(firebaseConfig); auth=getAuth(app); db=getFirestore(app); functions=getFunctions(app,'us-central1'); auth.useDeviceLanguage();
  await setPersistence(auth,browserLocalPersistence);
  try{ await getRedirectResult(auth); }catch(error){ toast(errorMessage(error)); }
  onAuthStateChanged(auth,async user=>{
    stopListeners(); state.user=user;
    if(!user){ showAuth(); return; }
    try{ await setDoc(doc(db,'users',user.uid),{displayName:user.displayName||firstName(user),email:user.email||'',lastLoginAt:serverTimestamp()},{merge:true}); }
    catch(error){ console.error(error); toast(errorMessage(error)); }
    updateProfileUI(); showApp(); startListeners();
  });
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.error);
}

function bindEvents(){
  $$('.auth-tab').forEach(button=>button.addEventListener('click',()=>switchAuth(button.dataset.authTab)));
  $$('.show-password').forEach(button=>button.addEventListener('click',()=>{const input=button.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';button.textContent=input.type==='password'?'Ver':'Ocultar';}));
  $('#login-form').addEventListener('submit',loginEmail); $('#register-form').addEventListener('submit',registerEmail);
  $('#forgot-password').addEventListener('click',forgotPassword); $('#google-login').addEventListener('click',()=>socialLogin('google')); $('#apple-login').addEventListener('click',()=>socialLogin('apple'));
  $$('.bottom-nav button').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page))); $$('[data-go-page]').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.goPage)));
  $$('[data-month]').forEach(button=>button.addEventListener('click',()=>changeMonth(Number(button.dataset.month)))); $$('[data-open-transaction]').forEach(button=>button.addEventListener('click',()=>openTransaction()));
  $('#profile-button').addEventListener('click',()=>showPage('settings')); $('#add-account').addEventListener('click',()=>openModal('account-modal')); $('#add-goal').addEventListener('click',()=>openModal('goal-modal')); $('#manage-categories').addEventListener('click',()=>openModal('category-modal'));
  $$('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModal)); $('#modal-backdrop').addEventListener('click',event=>{if(event.target.id==='modal-backdrop')closeModal();});
  $$('[data-tx-type]').forEach(button=>button.addEventListener('click',()=>setTransactionType(button.dataset.txType))); $('#transaction-form').addEventListener('submit',saveTransaction); $('#account-form').addEventListener('submit',saveAccount); $('#goal-form').addEventListener('submit',saveGoal); $('#category-form').addEventListener('submit',saveCategory);
  $('#delete-transaction').addEventListener('click',()=>{const id=state.editingTxId;if(id)confirmDeleteItem('transaction',id);});
  $$('#tx-filters button').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.filter;$$('#tx-filters button').forEach(item=>item.classList.toggle('active',item===button));renderTransactions();}));
  $('#logout').addEventListener('click',()=>signOut(auth)); $('#edit-profile').addEventListener('click',editProfile); $('#send-reset').addEventListener('click',sendPasswordChange); $('#export-data').addEventListener('click',exportCSV); $('#delete-account').addEventListener('click',requestDeleteAccount); $('#resend-verification').addEventListener('click',resendVerification);
  $('#confirm-action').addEventListener('click',()=>confirmHandler?.());
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#install-app').hidden=false;}); $('#install-app').addEventListener('click',installApp);
}

async function loginEmail(event){ event.preventDefault();setBusy('#login-form',true);try{await signInWithEmailAndPassword(auth,$('#login-email').value.trim(),$('#login-password').value);}catch(error){toast(errorMessage(error));}finally{setBusy('#login-form',false);} }
async function registerEmail(event){ event.preventDefault();setBusy('#register-form',true);try{const credential=await createUserWithEmailAndPassword(auth,$('#register-email').value.trim(),$('#register-password').value);await updateProfile(credential.user,{displayName:$('#register-name').value.trim()});if(state.user)updateProfileUI();await sendEmailVerification(credential.user);toast('¡Cuenta creada! Te hemos enviado un correo de confirmación.');}catch(error){toast(errorMessage(error));}finally{setBusy('#register-form',false);} }
async function forgotPassword(){ const email=$('#login-email').value.trim();if(!email){toast('Introduce primero tu correo electrónico.');return;}try{await sendPasswordResetEmail(auth,email);toast('Te hemos enviado el enlace de recuperación.');}catch(error){toast(errorMessage(error));} }
async function socialLogin(kind){ try{let provider;if(kind==='google'){provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});}else{provider=new OAuthProvider('apple.com');provider.addScope('email');provider.addScope('name');provider.setCustomParameters({locale:'es_ES'});}if(matchMedia('(max-width: 760px)').matches||matchMedia('(display-mode: standalone)').matches)await signInWithRedirect(auth,provider);else await signInWithPopup(auth,provider);}catch(error){toast(errorMessage(error));} }

function startListeners(){ const base=collection(db,'users',state.user.uid,'transactions');state.unsubscribers=[onSnapshot(query(base,orderBy('createdAt','desc')),snap=>{state.transactions=snap.docs.map(item=>({id:item.id,...item.data()}));renderAll();},syncError),onSnapshot(query(collection(db,'users',state.user.uid,'accounts'),orderBy('createdAt','asc')),snap=>{state.accounts=snap.docs.map(item=>({id:item.id,...item.data()}));renderAll();},syncError),onSnapshot(query(collection(db,'users',state.user.uid,'goals'),orderBy('createdAt','asc')),snap=>{state.goals=snap.docs.map(item=>({id:item.id,...item.data()}));renderGoals();},syncError),onSnapshot(query(collection(db,'users',state.user.uid,'categories'),orderBy('createdAt','asc')),snap=>{state.categories=snap.docs.map(item=>({id:item.id,...item.data()}));renderCategories();},syncError)]; }
function stopListeners(){state.unsubscribers.forEach(unsubscribe=>unsubscribe());state.unsubscribers=[];state.transactions=[];state.accounts=[];state.goals=[];state.categories=[];}
function syncError(error){console.error(error);toast('No se han podido sincronizar tus datos.');}
function userCollection(name){return collection(db,'users',state.user.uid,name);}

function updateProfileUI(){ const name=state.user.displayName||firstName();const initial=firstName().charAt(0).toUpperCase();$('#greeting-name').textContent=`¡Hola, ${firstName()}!`;const hour=new Date().getHours();$('#greeting-period').textContent=hour<12?'Buenos días':hour<20?'Buenas tardes':'Buenas noches';$('#profile-button').textContent=initial;$('#settings-avatar').textContent=initial;$('#settings-name').textContent=name;$('#settings-email').textContent=state.user.email||'Cuenta de Apple';$('#email-banner').hidden=!state.user.email||state.user.emailVerified;}
function showPage(page){$$('.page').forEach(item=>item.classList.toggle('active',item.id===`page-${page}`));$$('.bottom-nav button').forEach(button=>button.classList.toggle('active',button.dataset.page===page));scrollTo({top:0,behavior:'smooth'});}
function changeMonth(delta){state.month+=delta;if(state.month>11){state.month=0;state.year++;}if(state.month<0){state.month=11;state.year--;}renderAll();}
function renderAll(){renderDashboard();renderTransactions();renderAccounts();renderGoals();}

function renderDashboard(){ const items=monthTransactions(),income=items.filter(i=>i.type==='income').reduce((s,i)=>s+Number(i.amount),0),expense=items.filter(i=>i.type==='expense').reduce((s,i)=>s+Number(i.amount),0),result=income-expense,total=state.accounts.reduce((s,a)=>s+accountBalance(a),0);const label=`${MONTHS[state.month]} ${state.year}`;$('#home-month').textContent=label;$('#tx-month').textContent=label;$('#total-balance').textContent=money(total);$('#account-count').textContent=`${state.accounts.length} ${state.accounts.length===1?'cuenta registrada':'cuentas registradas'}`;$('#month-income').textContent=money(income);$('#month-expense').textContent=money(expense);$('#month-result').textContent=money(result);$('#month-result').style.color=result<0?'var(--red)':'var(--green)';const rate=income>0?Math.round(result/income*100):0;$('#savings-rate').textContent=`${rate} % ahorrado`;$('#month-progress').style.width=`${Math.max(0,Math.min(100,rate))}%`;renderCategoryBreakdown(items);renderTransactionList($('#recent-transactions'),items.slice(0,4)); }
function renderCategoryBreakdown(items){const sums={};items.filter(i=>i.type==='expense').forEach(i=>sums[i.category]=(sums[i.category]||0)+Number(i.amount));const rows=Object.entries(sums).sort((a,b)=>b[1]-a[1]),el=$('#category-breakdown');if(!rows.length){el.className='list-card empty-box';el.textContent='No hay gastos este mes.';return;}const max=rows[0][1];el.className='list-card';el.innerHTML=rows.map(([name,value])=>`<div class="category-row"><div class="category-line"><span>${esc(name)}</span><strong>${money(value)}</strong></div><div class="category-track"><div style="width:${value/max*100}%"></div></div></div>`).join('');}
function renderTransactions(){let items=monthTransactions();if(state.filter!=='all')items=items.filter(item=>item.type===state.filter);renderTransactionList($('#all-transactions'),items);}
function renderTransactionList(el,items){if(!items.length){el.innerHTML='<div class="empty-state">Todavía no hay movimientos.</div>';return;}el.innerHTML=items.map(item=>`<article class="transaction-item"><div class="transaction-icon">${ICONS[item.category]||'•'}</div><div class="transaction-main"><strong>${esc(item.description)}</strong><small>${dateES(item.date)} · ${esc(item.category)}${item.type==='income'&&item.paymentMethod?` · ${PAYMENT_METHODS[item.paymentMethod]||'Otro origen'}`:''}</small></div><span class="amount ${item.type}">${item.type==='income'?'+':'−'} ${money(item.amount)}</span><button class="item-menu" data-edit-tx="${item.id}" aria-label="Editar movimiento">›</button></article>`).join('');el.querySelectorAll('[data-edit-tx]').forEach(button=>button.addEventListener('click',()=>openTransaction(button.dataset.editTx)));}
function renderAccounts(){const total=state.accounts.reduce((s,a)=>s+accountBalance(a),0);$('#accounts-total').textContent=money(total);const el=$('#accounts-list');if(!state.accounts.length){el.innerHTML='<div class="empty-state">Añade tu primera cuenta o cartera.</div>';return;}el.innerHTML=state.accounts.map(account=>`<article class="account-item" style="--account-color:${account.color||'var(--blue)'}"><div class="account-icon">▣</div><div class="account-info"><strong>${esc(account.name)}</strong><span>${accountType(account.type)}</span></div><div class="account-value">${money(accountBalance(account))}</div><button class="item-menu" data-delete-account-id="${account.id}" aria-label="Eliminar cuenta">×</button></article>`).join('');el.querySelectorAll('[data-delete-account-id]').forEach(button=>button.addEventListener('click',()=>confirmDeleteItem('account',button.dataset.deleteAccountId)));}
function accountType(type){return {checking:'Cuenta corriente',wallet:'Efectivo',savings:'Ahorro',investment:'Inversión',other:'Otra cuenta'}[type]||'Cuenta';}
function renderGoals(){const el=$('#goals-list');if(!state.goals.length){el.innerHTML='<div class="empty-state">Crea un objetivo para seguir tus planes.</div>';return;}el.innerHTML=state.goals.map(goal=>{const pct=Math.min(100,Math.round(Number(goal.saved||0)/Number(goal.target||1)*100));return `<article class="goal-item"><div class="goal-top"><strong>${esc(goal.name)}</strong><span>${pct}%</span></div><div class="goal-track"><div style="width:${pct}%"></div></div><div class="goal-details"><span>${money(goal.saved)} ahorrados</span><span>Objetivo ${money(goal.target)}</span></div><button class="text-button" data-update-goal="${goal.id}">Actualizar importe</button></article>`;}).join('');el.querySelectorAll('[data-update-goal]').forEach(button=>button.addEventListener('click',()=>updateGoalValue(button.dataset.updateGoal)));}

function setTransactionType(type){state.txType=type;$$('[data-tx-type]').forEach(button=>button.classList.toggle('active',button.dataset.txType===type));$('#tx-origin-field').hidden=type!=='income';$('#tx-category').innerHTML=categoriesFor(type).map(name=>`<option>${esc(name)}</option>`).join('');}
function openTransaction(id=null){state.editingTxId=id;const item=id?state.transactions.find(tx=>tx.id===id):null;openModal('transaction-modal');$('#transaction-modal-title').textContent=item?'Editar movimiento':'Nuevo movimiento';$('#delete-transaction').hidden=!item;setTransactionType(item?.type||'expense');$('#tx-description').value=item?.description||'';$('#tx-amount').value=item?.amount||'';$('#tx-date').value=item?.date||new Date().toISOString().slice(0,10);$('#tx-category').value=item?.category||categoriesFor(state.txType)[0];$('#tx-origin').value=item?.paymentMethod||'pix';$('#tx-account').innerHTML='<option value="">Sin cuenta vinculada</option>'+state.accounts.map(account=>`<option value="${account.id}">${esc(account.name)}</option>`).join('');$('#tx-account').value=item?.accountId||'';}
async function saveTransaction(event){event.preventDefault();const accountId=$('#tx-account').value,account=state.accounts.find(item=>item.id===accountId);const data={type:state.txType,description:$('#tx-description').value.trim(),amount:Number($('#tx-amount').value),date:$('#tx-date').value,category:$('#tx-category').value,accountId,accountName:account?.name||'',paymentMethod:state.txType==='income'?$('#tx-origin').value:'',updatedAt:serverTimestamp()};if(!data.description||!data.amount||!data.date)return;setBusy('#transaction-form',true);try{if(state.editingTxId)await updateDoc(doc(db,'users',state.user.uid,'transactions',state.editingTxId),data);else await addDoc(userCollection('transactions'),{...data,createdAt:serverTimestamp()});closeModal();toast('Movimiento guardado.');}catch(error){toast(errorMessage(error));}finally{setBusy('#transaction-form',false);} }
async function saveAccount(event){event.preventDefault();setBusy('#account-form',true);try{await addDoc(userCollection('accounts'),{name:$('#account-name').value.trim(),type:$('#account-type').value,openingBalance:Number($('#account-opening').value||0),color:$('#account-color').value,createdAt:serverTimestamp()});event.target.reset();closeModal();toast('Cuenta creada.');}catch(error){toast(errorMessage(error));}finally{setBusy('#account-form',false);} }
async function saveGoal(event){event.preventDefault();setBusy('#goal-form',true);try{await addDoc(userCollection('goals'),{name:$('#goal-name').value.trim(),target:Number($('#goal-target').value),saved:Number($('#goal-saved').value||0),deadline:$('#goal-deadline').value,createdAt:serverTimestamp()});event.target.reset();closeModal();toast('Objetivo creado.');}catch(error){toast(errorMessage(error));}finally{setBusy('#goal-form',false);} }
async function saveCategory(event){event.preventDefault();const name=$('#category-name').value.trim(),type=$('#category-type').value;if(categoriesFor(type).some(item=>item.toLocaleLowerCase('es-ES')===name.toLocaleLowerCase('es-ES'))){toast('Esta categoría ya existe.');return;}setBusy('#category-form',true);try{await addDoc(userCollection('categories'),{name,type,createdAt:serverTimestamp()});event.target.reset();closeModal();toast('Categoría creada.');}catch(error){toast(errorMessage(error));}finally{setBusy('#category-form',false);} }
function renderCategories(){const el=$('#custom-categories');if(!state.categories.length){el.innerHTML='';el.hidden=true;return;}el.hidden=false;el.innerHTML=state.categories.map(category=>`<button data-delete-category="${category.id}"><span>${esc(category.name)} · ${category.type==='income'?'Ingreso':'Gasto'}</span><span>×</span></button>`).join('');el.querySelectorAll('[data-delete-category]').forEach(button=>button.addEventListener('click',()=>openConfirm('¿Eliminar categoría?','Los movimientos anteriores conservarán el nombre de esta categoría.',async()=>{try{await deleteDoc(doc(db,'users',state.user.uid,'categories',button.dataset.deleteCategory));closeModal();toast('Categoría eliminada.');}catch(error){toast(errorMessage(error));}})));}
async function updateGoalValue(id){const goal=state.goals.find(item=>item.id===id);const value=prompt(`¿Cuánto has ahorrado ya para «${goal.name}»?`,goal.saved||0);if(value===null)return;const amount=Number(String(value).replace(',','.'));if(Number.isNaN(amount)||amount<0){toast('Introduce un importe válido.');return;}try{await updateDoc(doc(db,'users',state.user.uid,'goals',id),{saved:amount,updatedAt:serverTimestamp()});toast('Objetivo actualizado.');}catch(error){toast(errorMessage(error));}}
function confirmDeleteItem(kind,id){const isAccount=kind==='account';openConfirm(`¿Eliminar ${isAccount?'la cuenta':'el movimiento'}?`,isAccount?'Los movimientos se conservarán, pero dejarán de estar vinculados visualmente a esta cuenta.':'Esta acción no se puede deshacer.',async()=>{try{await deleteDoc(doc(db,'users',state.user.uid,isAccount?'accounts':'transactions',id));closeModal();toast('Elemento eliminado.');}catch(error){toast(errorMessage(error));}});}

async function editProfile(){const name=prompt('¿Cómo quieres que te llamemos?',state.user.displayName||'');if(!name?.trim())return;try{await updateProfile(state.user,{displayName:name.trim()});await setDoc(doc(db,'users',state.user.uid),{displayName:name.trim()},{merge:true});updateProfileUI();toast('Nombre actualizado.');}catch(error){toast(errorMessage(error));}}
async function sendPasswordChange(){if(!state.user.email){toast('Tu cuenta utiliza acceso social.');return;}try{await sendPasswordResetEmail(auth,state.user.email);toast('Te hemos enviado el enlace para cambiar tu contraseña.');}catch(error){toast(errorMessage(error));}}
async function resendVerification(){try{await sendEmailVerification(state.user);toast('Correo de confirmación reenviado.');}catch(error){toast(errorMessage(error));}}
function exportCSV(){if(!state.transactions.length){toast('No hay movimientos para exportar.');return;}const cell=value=>`"${String(value??'').replace(/"/g,'""')}"`;const rows=state.transactions.map(item=>[item.date,item.type==='income'?'Ingreso':'Gasto',cell(item.description),cell(item.category),PAYMENT_METHODS[item.paymentMethod]||'',Number(item.amount).toFixed(2).replace('.',','),cell(item.accountName)].join(';'));const blob=new Blob(['\uFEFFFecha;Tipo;Descripción;Categoría;Origen;Importe;Cuenta\n',...rows.map(row=>row+'\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`vault-movimientos-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);toast('Archivo exportado.');}
function requestDeleteAccount(){openConfirm('¿Eliminar tu cuenta?','Todos los movimientos, cuentas y objetivos se eliminarán de forma permanente. Escribe ELIMINAR para confirmar.',async()=>{if($('#confirm-input').value.trim().toUpperCase()!=='ELIMINAR'){toast('Escribe ELIMINAR para confirmar.');return;}$('#confirm-action').disabled=true;try{await httpsCallable(functions,'deleteVaultAccount')();closeModal();toast('Tu cuenta ha sido eliminada.');}catch(error){toast(errorMessage(error));}finally{$('#confirm-action').disabled=false;}},true);}
function openConfirm(title,message,handler,requiresInput=false){openModal('confirm-modal');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;$('#confirm-input-wrap').hidden=!requiresInput;$('#confirm-input').value='';confirmHandler=handler;}
function openModal(id){$('#modal-backdrop').hidden=false;$$('#modal-backdrop .modal').forEach(modal=>modal.hidden=modal.id!==id);}
function closeModal(){ $('#modal-backdrop').hidden=true;$$('#modal-backdrop .modal').forEach(modal=>modal.hidden=true);confirmHandler=null;state.editingTxId=null; }
async function installApp(){if(!deferredInstall)return;await deferredInstall.prompt();deferredInstall=null;$('#install-app').hidden=true;}

start().catch(error=>{console.error(error);showAuth();toast('No se ha podido iniciar Vault.');});


